"""create_initial_tables

Revision ID: 7a5042c6a307
Revises: 
Create Date: 2025-05-13 18:51:50.647953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "7a5042c6a307"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "receipts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("store_name", sa.String(), nullable=True),
        sa.Column("purchase_date", sa.Date(), nullable=True),
        sa.Column("total_amount", sa.Float(), nullable=True),
        sa.Column("gdrive_file_id", sa.String(), nullable=True),
        sa.Column("gdrive_file_url", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gdrive_file_id"),
    )
    op.create_index(op.f("ix_receipts_id"), "receipts", ["id"], unique=False)
    op.create_index(
        op.f("ix_receipts_purchase_date"), "receipts", ["purchase_date"], unique=False
    )
    op.create_index(
        op.f("ix_receipts_store_name"), "receipts", ["store_name"], unique=False
    )
    op.create_table(
        "product_entries",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("original_name", sa.String(), nullable=False),
        sa.Column("generalized_name", sa.String(), nullable=False),
        sa.Column("price_per_unit", sa.Float(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("weight_volume_text", sa.String(), nullable=True),
        sa.Column("receipt_id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["receipt_id"],
            ["receipts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_product_entries_generalized_name"),
        "product_entries",
        ["generalized_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_entries_id"), "product_entries", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_product_entries_original_name"),
        "product_entries",
        ["original_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_product_entries_receipt_id"),
        "product_entries",
        ["receipt_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_entries_receipt_id"), table_name="product_entries")
    op.drop_index(
        op.f("ix_product_entries_original_name"), table_name="product_entries"
    )
    op.drop_index(op.f("ix_product_entries_id"), table_name="product_entries")
    op.drop_index(
        op.f("ix_product_entries_generalized_name"), table_name="product_entries"
    )
    op.drop_table("product_entries")
    op.drop_index(op.f("ix_receipts_store_name"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_purchase_date"), table_name="receipts")
    op.drop_index(op.f("ix_receipts_id"), table_name="receipts")
    op.drop_table("receipts")
    # ### end Alembic commands ###
